Repository ZDoom/gzdoom, pull requests merged in 2023-01, with the labels that each got.

#1967 [BUGFIX] Add missing methods (GetIfExists/CheckValue) to Map pseudo-generics
  src/common/engine/namedef.h
  src/common/scripting/core/types.cpp
Labels: PR bugfix, QZDoom Testing

#1968 Add some logs during soundfont selection
  src/common/audio/music/i_soundfont.cpp
Labels: PR new feature

#1961 Added GitHub CodeSpaces development environment.
  .devcontainer/GZDoom.dockerfile
  .devcontainer/devcontainer.json
Labels: PR low priority

#1969 Added check for invalid class on in-VM instantiation
  src/common/scripting/core/scopebarrier.cpp
Labels: PR bugfix, PR low priority

#1964 Added OnEngineInitialize() for static event handlers
  src/d_main.cpp
  src/events.cpp
  src/events.h
  wadsrc/static/zscript/events.zs
Labels: PR new feature, QZDoom Testing

#1394 Add cvars to fade sprite shadows progressively according to thing <-> floor distance
  src/rendering/hwrenderer/scene/hw_sprites.cpp
  src/rendering/r_utility.cpp
Labels: enhancement, on hold, QZDoom Testing

#1974 Fixed a bug where calling an invalid virtual function would cause a crash.
  src/common/scripting/vm/vmexec.h
Labels: PR bugfix, PR low priority

#1979 Added scroll bar for wad picker to Linux.
  src/common/platform/posix/unix/gtk_dialogs.cpp
Labels: PR bugfix

#1878 Zscript Custom CVars
  src/common/console/c_cvars.cpp
  src/common/console/c_cvars.h
  src/d_main.cpp
  wadsrc/static/zscript/engine/base.zs
Labels: PR low priority, PR new feature, QZDoom Testing
