Repository ZDoom/gzdoom, pull requests merged in 2023-02, with the labels that each got.

#1985 - add RedirectCVAR directive for loading alternate maps based on a Bo…
  src/g_level.cpp
  src/gamedata/g_mapinfo.cpp
  src/gamedata/g_mapinfo.h
Labels: PR new feature

#1982 Let custom CVar handlers be called on cloned cvars
  src/common/console/c_cvars.cpp
  src/common/console/c_cvars.h
  src/common/scripting/interface/vmnatives.cpp
  src/d_netinfo.cpp
Labels: PR low priority, PR new feature

#1983 Easier MacOS Compilation w/Open AL
  src/CMakeLists.txt
Labels: PR low priority, PR refactor/maintenance

#1991 Fixing GLES mode to work on real GLES hardware and OpenGL 2 again
  src/common/rendering/gles/gles_buffers.cpp
  src/common/rendering/gles/gles_hwtexture.cpp
  src/common/rendering/gles/gles_renderstate.cpp
  src/common/rendering/gles/gles_system.cpp
  src/common/rendering/gles/gles_system.h
Labels: PR bugfix
