Repository ZDoom/gzdoom, pull requests merged in 2023-08, with the labels that each got.

#1902 Allow custom MessageBox menu selector
  wadsrc/static/zscript/engine/ui/menu/custommessagebox.zs
  wadsrc/static/zscript/engine/ui/menu/messagebox.zs
Labels: PR new feature, QZDoom Testing

#1920 Added XF_THRUSTLESS, XF_NOALLIES and XF_CIRCULAR.
  src/playsim/p_local.h
  src/playsim/p_map.cpp
  src/scripting/vmthunks_actors.cpp
  wadsrc/static/zscript/actors/actor.zs
  wadsrc/static/zscript/actors/attacks.zs
  wadsrc/static/zscript/constants.zs
Labels: PR new feature, QZDoom Testing

#1950 Exported reflection functionality
  src/playsim/p_local.h
  src/playsim/p_map.cpp
  src/playsim/p_mobj.cpp
  src/scripting/vmthunks_actors.cpp
  wadsrc/static/zscript/actors/actor.zs
Labels: PR native export, QZDoom Testing

#1959 Fixed BlockingLine giving erroneous results
  src/p_setup.cpp
  src/playsim/actor.h
  src/playsim/p_mobj.cpp
  src/scripting/vmthunks_actors.cpp
  wadsrc/static/zscript/actors/actor.zs
Labels: PR bugfix, QZDoom Testing

#1960 Added virtual function for special bounce handling
  src/playsim/actor.h
  src/playsim/p_map.cpp
  src/playsim/p_mobj.cpp
  wadsrc/static/zscript/actors/actor.zs
Labels: PR new feature, QZDoom Testing

#633 Attempt to fix the "is" operator to work with readonly pointers
  src/common/scripting/backend/codegen.cpp
Labels: PR bugfix, QZDoom Testing

#2138 Inventory map change fix
  wadsrc/static/zscript/actors/player/player.zs
Labels: PR bugfix
