Repository ZDoom/gzdoom, pull requests merged in 2023-09, with the labels that each got.

#2149 [new feature] Add float.equal_epsilon and double.equal_epsilon
  src/common/engine/namedef.h
  src/common/scripting/core/types.cpp
Labels: PR new feature

#2002 [new feature, low priority] Expose OF_Transient to actors as bNoSaveGame
  src/common/engine/serializer.cpp
  src/common/objects/dobjtype.cpp
  src/scripting/thingdef_data.cpp
Labels: PR low priority, PR new feature

#1986 [low priority, new feature] Add Inventory::ModifyBob and Inventory::ModifyBob3D
  src/common/scripting/vm/vm.h
  src/playsim/p_pspr.cpp
  wadsrc/static/zscript/actors/inventory/inventory.zs
Labels: PR low priority, PR new feature

#2084 Fix a very rare crash with complex Polyobjects
  src/utility/nodebuilder/nodebuild.cpp
  src/utility/nodebuilder/nodebuild.h
Labels: PR bugfix

#1988 Add more information in saved game comments
  src/g_game.cpp
Labels: PR new feature
