Repository ZDoom/gzdoom, pull requests merged in 2024-01, with the labels that each got.

#2329 Minor reworks in iwadinfo.txt
  wadsrc_extra/static/iwadinfo.txt
Labels: PR refactor/maintenance

#2330 Player Portal Sprite Fix
  src/playsim/d_player.h
  src/playsim/p_local.h
  src/playsim/p_map.cpp
  src/playsim/p_mobj.cpp
  src/rendering/hwrenderer/scene/hw_sprites.cpp
  src/rendering/r_utility.cpp
  src/rendering/r_utility.h
Labels: PR bugfix

#2331 Exposed 'viewactive'
  src/g_game.cpp
  wadsrc/static/zscript/doombase.zs
Labels: PR new feature

#2295 Add Actor.CanReceive to let actors determine if they can receive an item
  wadsrc/static/zscript/actors/actor.zs
  wadsrc/static/zscript/actors/inventory/inventory.zs
Labels: PR new feature

#1975 Exposed ForceLightning() to ZScript. And added the ability to change the sound lightning makes.
  src/g_level.cpp
  src/g_levellocals.h
  src/gamedata/g_mapinfo.cpp
  src/gamedata/g_mapinfo.h
  src/playsim/mapthinkers/a_lightning.cpp
  src/playsim/mapthinkers/a_lightning.h
  src/scripting/vmthunks.cpp
  wadsrc/static/zscript/doombase.zs
Labels: PR low priority, PR new feature

#2348 Fixed int8 being written incorrectly to command buffer
  src/d_net.cpp
  src/d_net.h
  src/d_protocol.cpp
  src/d_protocol.h
Labels: critical / crash, PR bugfix

#2196 Add CenterText MENUDEF flag
  src/common/menu/menu.h
  src/common/menu/menudef.cpp
  wadsrc/static/zscript/engine/ui/menu/listmenu.zs
  wadsrc/static/zscript/engine/ui/menu/listmenuitems.zs
Labels: PR new feature
